"""add_music_file_to_content_plan

Revision ID: 1145add67fa0
Revises: 000000000001
Create Date: 2026-02-26 18:57:08.074648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1145add67fa0'
down_revision: Union[str, None] = '000000000001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _inspector():
    return sa.inspect(op.get_bind())


def _has_table(table_name: str) -> bool:
    try:
        return str(table_name) in set(_inspector().get_table_names())
    except Exception:
        return False


def _has_column(table_name: str, column_name: str) -> bool:
    try:
        cols = _inspector().get_columns(table_name)
        return str(column_name) in {str(c.get("name") or "") for c in cols}
    except Exception:
        return False


def upgrade() -> None:
    if _has_table("content_plans") and not _has_column("content_plans", "music_file"):
        with op.batch_alter_table('content_plans', schema=None) as batch_op:
            batch_op.add_column(sa.Column('music_file', sa.String(), nullable=True))

    if _has_table("books") and not _has_column("books", "user_id"):
        with op.batch_alter_table('books', schema=None) as batch_op:
            batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
            batch_op.create_index(op.f('ix_books_user_id'), ['user_id'], unique=False)
            batch_op.create_foreign_key('fk_books_users', 'users', ['user_id'], ['id'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint('fk_books_users', type_='foreignkey')
        batch_op.drop_index(op.f('ix_books_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('content_plans', schema=None) as batch_op:
        batch_op.drop_column('music_file')
    # ### end Alembic commands ###
