"""add_stock_and_elevenlabs_keys

Revision ID: 560e9fa07258
Revises: 68d376a7c67d
Create Date: 2026-02-27 11:48:35.988936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '560e9fa07258'
down_revision: Union[str, None] = '68d376a7c67d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _inspector():
    return sa.inspect(op.get_bind())


def _has_column(table_name: str, column_name: str) -> bool:
    try:
        cols = _inspector().get_columns(table_name)
        return str(column_name) in {str(c.get("name") or "") for c in cols}
    except Exception:
        return False


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        if not _has_column("settings", "pexels_api_key"):
            batch_op.add_column(sa.Column('pexels_api_key', sa.String(), nullable=True))
        if not _has_column("settings", "pixabay_api_key"):
            batch_op.add_column(sa.Column('pixabay_api_key', sa.String(), nullable=True))
        if not _has_column("settings", "elevenlabs_api_key"):
            batch_op.add_column(sa.Column('elevenlabs_api_key', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('elevenlabs_api_key')
        batch_op.drop_column('pixabay_api_key')
        batch_op.drop_column('pexels_api_key')

    # ### end Alembic commands ###
