"""add_music_file_to_content_plan

Revision ID: 68d376a7c67d
Revises: 1145add67fa0
Create Date: 2026-02-26 19:01:06.682182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68d376a7c67d'
down_revision: Union[str, None] = '1145add67fa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channel_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_channel_reports_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_channel_reports_users', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_customers_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_customers_users', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_leads_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_leads_users', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('scheduled_videos', schema=None) as batch_op:
        # Check if index exists before creating to avoid error if it was manually created
        # But batch mode recreates table so it should be fine? 
        # Actually batch mode creates a new table, copies data, so we must define all constraints/indexes.
        batch_op.create_index(batch_op.f('ix_scheduled_videos_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_scheduled_videos_users', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.alter_column('suno_api_key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_settings_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_settings_users', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key('fk_users_tenants', 'tenants', ['tenant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_tenants', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_tenant_id'))

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_settings_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_settings_user_id'))
        batch_op.alter_column('suno_api_key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('scheduled_videos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_scheduled_videos_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_scheduled_videos_user_id'))

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_constraint('fk_leads_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_leads_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_customers_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_customers_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('channel_reports', schema=None) as batch_op:
        batch_op.drop_constraint('fk_channel_reports_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_channel_reports_user_id'))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
