"""add_unified_videos_pipeline_table

Cria a tabela central `unified_videos` do Pipeline Único de Vídeo do Codexia.
Contempla:
  - colunas de identidade, contrato, providers/custo, estado/progresso, artefatos, publicação, timestamps;
  - UNIQUE em idempotency_key (1 idempotency = 1 linha);
  - FKs para video_tasks e users (ON DELETE SET NULL para manter histórico);
  - índices em colunas de busca frequentes (status, módulo de origem, task_id, user_id, current_step);
  - idempotência (IF NOT EXISTS) para upgrade seguro;
  - downgrade seguro com CASCADE em índices/tabela.

Revision ID: a9b2c4d6e8f0
Revises: ab12cd34ef56
Create Date: 2026-08-06 09:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "a9b2c4d6e8f0"
down_revision: Union[str, None] = "ab12cd34ef56"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_TABLE = "unified_videos"


def _inspector():
    return sa.inspect(op.get_bind())


def _has_table(name: str) -> bool:
    return name in (_inspector().get_table_names() or [])


def _has_index(index_name: str, table_name: str = _TABLE) -> bool:
    return any(
        str(idx.get("name") or "").lower() == str(index_name).lower()
        for idx in (_inspector().get_indexes(table_name) or [])
    )


def upgrade() -> None:
    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS {_TABLE} (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            idempotency_key VARCHAR(255) NOT NULL,
            task_id VARCHAR(64) NULL,
            source_module VARCHAR(64) NOT NULL,
            source_id VARCHAR(191) NOT NULL,
            user_id INTEGER NULL,
            content_type VARCHAR(64) NOT NULL DEFAULT 'devotional',
            topic TEXT NULL,
            script_text TEXT NULL,
            duration_minutes INTEGER NOT NULL DEFAULT 3,
            aspect_ratio VARCHAR(12) NOT NULL DEFAULT '16:9',
            image_count INTEGER NOT NULL DEFAULT 8,
            visibility VARCHAR(32) NOT NULL DEFAULT 'unlisted',
            review_required BOOLEAN NOT NULL DEFAULT TRUE,
            auto_publish BOOLEAN NOT NULL DEFAULT FALSE,
            force_regenerate BOOLEAN NOT NULL DEFAULT FALSE,
            text_provider VARCHAR(64) NULL,
            text_model VARCHAR(64) NULL,
            image_provider VARCHAR(64) NULL,
            image_model VARCHAR(64) NULL,
            voice_provider VARCHAR(64) NULL,
            voice_model VARCHAR(64) NULL,
            call_count_text INTEGER NOT NULL DEFAULT 0,
            call_count_image INTEGER NOT NULL DEFAULT 0,
            call_count_audio INTEGER NOT NULL DEFAULT 0,
            estimated_cost DOUBLE PRECISION NOT NULL DEFAULT 0.0,
            actual_cost DOUBLE PRECISION NOT NULL DEFAULT 0.0,
            status VARCHAR(32) NOT NULL DEFAULT 'queued',
            current_step VARCHAR(32) NULL,
            progress INTEGER NOT NULL DEFAULT 0,
            last_message TEXT NULL,
            last_error TEXT NULL,
            script_json TEXT NULL,
            storyboard_json TEXT NULL,
            images_json TEXT NULL,
            result_json TEXT NULL,
            audio_path TEXT NULL,
            audio_size_bytes INTEGER NULL,
            audio_duration_seconds DOUBLE PRECISION NULL,
            video_path TEXT NULL,
            video_url TEXT NULL,
            video_size_bytes INTEGER NULL,
            video_duration_seconds DOUBLE PRECISION NULL,
            cover_path TEXT NULL,
            cover_url TEXT NULL,
            youtube_video_id TEXT NULL,
            youtube_url TEXT NULL,
            published_at TIMESTAMP WITHOUT TIME ZONE NULL,
            approved_at TIMESTAMP WITHOUT TIME ZONE NULL,
            created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
            updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
        )
        """
    )

    # UNIQUE(idempotency_key)
    op.execute(
        f"""
        CREATE UNIQUE INDEX IF NOT EXISTS ux_{_TABLE}_idempotency_key
        ON {_TABLE} (idempotency_key)
        """
    )

    # FK para video_tasks(id) — referência fraca: apagar video_task NÃO apaga unified_video
    op.execute(
        f"""
        DO $$ BEGIN
          IF NOT EXISTS (
              SELECT 1 FROM pg_constraint
              WHERE conname = 'fk_{_TABLE}_task_id_video_tasks'
          ) THEN
              ALTER TABLE {_TABLE}
              ADD CONSTRAINT fk_{_TABLE}_task_id_video_tasks
              FOREIGN KEY (task_id) REFERENCES video_tasks(id)
              ON DELETE SET NULL ON UPDATE CASCADE;
          END IF;
        END $$;
        """
    )

    # FK para users(id)
    op.execute(
        f"""
        DO $$ BEGIN
          IF NOT EXISTS (
              SELECT 1 FROM pg_constraint
              WHERE conname = 'fk_{_TABLE}_user_id_users'
          ) THEN
              ALTER TABLE {_TABLE}
              ADD CONSTRAINT fk_{_TABLE}_user_id_users
              FOREIGN KEY (user_id) REFERENCES users(id)
              ON DELETE SET NULL ON UPDATE CASCADE;
          END IF;
        END $$;
        """
    )

    # Índices para filtros frequentes
    for idx_sql in [
        f"CREATE INDEX IF NOT EXISTS ix_{_TABLE}_source_module ON {_TABLE} (source_module)",
        f"CREATE INDEX IF NOT EXISTS ix_{_TABLE}_source_id ON {_TABLE} (source_id)",
        f"CREATE INDEX IF NOT EXISTS ix_{_TABLE}_task_id ON {_TABLE} (task_id)",
        f"CREATE INDEX IF NOT EXISTS ix_{_TABLE}_user_id ON {_TABLE} (user_id)",
        f"CREATE INDEX IF NOT EXISTS ix_{_TABLE}_status ON {_TABLE} (status)",
        f"CREATE INDEX IF NOT EXISTS ix_{_TABLE}_current_step ON {_TABLE} (current_step)",
    ]:
        op.execute(idx_sql)


def downgrade() -> None:
    # Remove índices e tabela (se existirem)
    for stmt in [
        f"DROP INDEX IF EXISTS ux_{_TABLE}_idempotency_key CASCADE",
        f"DROP INDEX IF EXISTS ix_{_TABLE}_source_module CASCADE",
        f"DROP INDEX IF EXISTS ix_{_TABLE}_source_id CASCADE",
        f"DROP INDEX IF EXISTS ix_{_TABLE}_task_id CASCADE",
        f"DROP INDEX IF EXISTS ix_{_TABLE}_user_id CASCADE",
        f"DROP INDEX IF EXISTS ix_{_TABLE}_status CASCADE",
        f"DROP INDEX IF EXISTS ix_{_TABLE}_current_step CASCADE",
        f"DROP TABLE IF EXISTS {_TABLE} CASCADE",
    ]:
        op.execute(stmt)
